version: "3.9"

services:

  db:
    image: postgres:13-alpine
    ports:
      - 54320:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=inventory
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_admin -d inventory" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test

  inventory:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    environment:
      - DB_USER=db_admin
      - DB_PASS=db_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=inventory
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test

networks:
  test:
    name: test